const assert = require('node:assert/strict');
require('../js/sauts-common.js');
require('../js/github-sauts.js');
const entry={id:'saut-11111111-2222-4333-8444-555555555555',date:'2027-01-02',time:'18:00',title:'Un souvenir',message:'Texte avec é et <script> comme texte.',photos:[]};
assert.equal(DorySauts.displayDate(entry.date),'02/01/2027');
assert.throws(()=>DorySauts.validateDate('2026-02-30'));
assert.throws(()=>DorySauts.validateData({version:1,entries:[entry,entry]}));
assert.throws(()=>DorySauts.validateData({version:1,entries:[{...entry,date:'2025-04-14'}]}));
assert.throws(()=>DorySauts.validateData({version:1,entries:[{...entry,photos:[{path:'../../secret',caption:''}]}]}));
assert.equal(DorySauts.validateData({version:1,entries:[entry]}).entries.length,1);
assert.throws(()=>new DoryGitClient('fake','main','../'));
(async()=>{
  const calls=[];
  global.fetch=async (url,opts)=>{
    calls.push({url,opts,body:opts.body?JSON.parse(opts.body):null});
    let body={};
    if(url.includes('/git/ref/'))body={object:{sha:'head1'}};
    else if(url.endsWith('/git/blobs'))body={sha:'blob'+calls.length};
    else if(url.endsWith('/git/trees'))body={sha:'tree2'};
    else if(url.endsWith('/git/commits'))body={sha:'commit2'};
    else if(url.includes('/git/refs/'))body={object:{sha:'commit2'}};
    else throw Error('Unexpected '+url);
    return {ok:true,status:200,json:async()=>body};
  };
  const client=new DoryGitClient('TEST_NOT_A_REAL_TOKEN','publish');
  const snap={head:'head1',tree:'base1',map:new Map(),data:{version:1,entries:[]}};
  const image={path:'photos/'+entry.date+'_'+entry.id+'_1.jpg',caption:'Légende',base64:'AA=='};
  const e={...entry,photos:[{path:image.path,caption:image.caption}]};
  const sha=await client.publish(snap,e,[image]);assert.equal(sha,'commit2');
  const tree=calls.find(c=>c.url.endsWith('/git/trees'));assert.equal(tree.body.base_tree,'base1');assert.equal(tree.body.tree.length,2);
  assert(tree.body.tree.some(x=>x.path==='data/sauts.json'));assert(tree.body.tree.some(x=>x.path===image.path));
  const update=calls.find(c=>c.opts.method==='PATCH');assert.equal(update.body.force,false);
  assert.equal(calls.filter(c=>c.opts.method==='PATCH').length,1);
  const jsonBlob=calls.filter(c=>c.url.endsWith('/git/blobs'))[1];
  const data=JSON.parse(Buffer.from(jsonBlob.body.content,'base64').toString('utf8'));assert.equal(data.entries[0].message,entry.message);
  let writes=0;
  global.fetch=async (_u,o)=>{if(o.method!=='GET')writes++;return {ok:true,status:200,json:async()=>({object:{sha:'someone-else'}})};};
  await assert.rejects(()=>client.publish(snap,e,[image]),/branche a changé/);assert.equal(writes,0);
  client.clear();await assert.rejects(()=>client.api(''),/Jeton manquant/);
  console.log('PASS: dates, schema, reserved memories, path safety, grouped commit, Unicode, non-forced update, concurrent change refusal and logout.');
})().catch(e=>{console.error(e);process.exitCode=1;});
